#!/usr/bin/env node

// Updates  @tensorflow/tfjs dependency to the specified version
// ex: ./update-tfjs-version 0.13.2

const fs = require('fs');
const path = require('path');

const tfjsTag = '@tensorflow/tfjs';
const tfjsNodeTag = '@tensorflow/tfjs-node';

if (process.argv.length !== 3) {
  console.log('Usage: update-tfjs-version <TARGET_TFJS_VER>`');
  process.exit(1);
}
const targetTfjsVer = process.argv[2];

const dirItems = fs.readdirSync(__dirname);
for (const item of dirItems) {
  if (fs.lstatSync(item).isDirectory()) {
    const dirPath = path.join(__dirname, item);
    const packageJsonPath = path.join(dirPath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath));
      const deps = packageJson['dependencies'];
      if (deps == null) {
        continue;
      }

      const devDeps = packageJson['devDependencies'];
      if (deps[tfjsNodeTag] != null ||
          devDeps != null && devDeps[tfjsNodeTag] != null) {
        console.log(
            `*** Skipping example with dependency or devDependency ` +
            `on tfjs-node: ${item}`);
        continue;
      }

      const targetVer = `^${targetTfjsVer}`;
      if (deps[tfjsTag] != null) {
        if (deps[tfjsTag] === targetVer) {
          console.log(`${item}: Already at target version (${targetVer})`);
        } else {
          const oldVer = deps[tfjsTag];
          deps[tfjsTag] = targetVer;
          fs.writeFileSync(
              packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
          console.log(`${item}: ${oldVer} --> ${targetVer}`);
        }
      }
    }
  }
}
